// play
export const RECEIVE_SINGER_LIST = 'RECEIVE_SINGER_LIST'

export const RECEIVE_SINGER_DETAIL = 'RECEIVE_SINGER_DETAIL'

export const RESET_SINGER_DETAIL = 'RESET_SINGER_DETAIL'

export const SET_CURRENT_SINGER = 'SET_CURRENT_SINGER'

export const SET_PLAY_SONG = 'SET_PLAY_SONG'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_PLAYING_STATUS = 'SET_PLAYING_STATUS'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

export const SET_PLAY_MODE = 'SET_PLAY_MODE'

export const SET_PLAY_LIST = 'SET_PLAY_LIST'

export const SET_PLAY_HISTORY = 'SET_PLAY_HISTORY'

// playList
export const DEL_PLAY_SONG = 'DEL_PLAY_SONG'

export const DEL_PLAY_SONG_LIST = 'DEL_PLAY_SONG_LIST'

// recommend
export const RECEIVE_RECOMMEND_DETAIL = 'RECEIVE_RECOMMEND_DETAIL'

export const RESET_RECOMMEND_DETAIL = 'RESET_RECOMMEND_DETAIL'

// rank
export const RECEIVE_RANK_LIST = 'RECEIVE_RANK_LIST'

export const RECEIVE_RANK_DETAIL = 'RECEIVE_RANK_DETAIL'

export const RESET_RANK_DETAIL = 'RESET_RANK_DETAIL'

// search
export const RECEIVE_HOT_SEARCH = 'RECEIVE_HOT_SEARCH'

export const RECEIVE_SEARCH_QUERY = 'RECEIVE_SEARCH_QUERY'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'

export const DELE_SEARCH_HISTORY = 'DELE_SEARCH_HISTORY'

export const DELE_SEARCH_HISTORY_LIST = 'DELE_SEARCH_HISTORY_LIST'

// song
export const SET_SONG_LYRIC = 'SET_SONG_LYRIC'

// user
export const ADD_FAVORITE_SONG = 'ADD_FAVORITE_SONG'

export const DEL_FAVORITE_SONG = 'DEL_FAVORITE_SONG'