// play
export const RECEIVE_SINGER_LIST = 'RECEIVE_SINGER_LIST'

export const RECEIVE_SINGER_DETAIL = 'RECEIVE_SINGER_DETAIL'

export const RESET_SINGER_DETAIL = 'RESET_SINGER_DETAIL'

export const SET_CURRENT_SINGER = 'SET_CURRENT_SINGER'

export const SET_PLAY_SONG = 'SET_PLAY_SONG'

export const SET_FULL_SCREEN = 'SET_FULL_SCREEN'

export const SET_PLAYING_STATUS = 'SET_PLAYING_STATUS'

export const SET_CURRENT_INDEX = 'SET_CURRENT_INDEX'

// recommend
export const RECEIVE_RECOMMEND_DETAIL = 'RECEIVE_RECOMMEND_DETAIL'

export const RESET_RECOMMEND_DETAIL = 'RESET_RECOMMEND_DETAIL'

// rank
export const RECEIVE_RANK_LIST = 'RECEIVE_RANK_LIST'

export const RECEIVE_RANK_DETAIL = 'RECEIVE_RANK_DETAIL'

export const RESET_RANK_DETAIL = 'RESET_RANK_DETAIL'

// search
export const RECEIVE_HOT_SEARCH = 'RECEIVE_HOT_SEARCH'

export const RECEIVE_SEARCH_QUERY = 'RECEIVE_SEARCH_QUERY'

export const SET_SEARCH_HISTORY = 'SET_SEARCH_HISTORY'