export const RECEIVE_SINGER_LIST = 'RECEIVE_SINGER_LIST';

export const RECEIVE_SINGER_DETAIL = 'RECEIVE_SINGER_DETAIL';

export const RESET_SINGER_DETAIL = 'RESET_SINGER_DETAIL';

export const SET_CURRENT_SINGER = 'SET_CURRENT_SINGER';

export const SET_PLAY_SONG = 'SET_PLAY_SONG';